version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1  //Pulling a docker image
    working_directory: ~/repo //going inside the container dir
    steps:
      - checkout //pulls the code from github to container
      # Download and cache dependencies
      - restore_cache: //create a cache
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:// run the commands
          name: Install dependencies
          command: npm install
      - save_cache: //saving the cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: //running the test cases
          name: Running tests
          command: npm test
  deploy: // deploy step
    docker:
      - image: circleci/node:chakracore-8.11.1 //pulling a container image
    steps:
      - run:
          name: AWS EC2 deploy 
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.236.1.107 \
            "echo Start deploy && \
            cd ~/circleci-aws && \
            git pull && \
            npm i && \
            npm run build && \
            pm2 stop build/server && \
            pm2 start build/server && \
            echo Deploy end"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
